server:
  port: 8080
  servlet:
    session:
      timeout: 1800
      cookie:
        max-age: 1800
        #name: SID # 세션 쿠키의 이름
        #http-only: true # 이 값이 true로 설정되면 JavaScript에서 세션 쿠키에 접근 X
        #secure: true  # 이 값이 true로 설정되면 HTTPS 연결에서만 세션 쿠키를 전송
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-stacktrace: never

# 2.4 +
spring:
  config:
    activate:
      on-profile: local
logging:
  file:
    path: C:/Users/jsper/log
    filename: local_log 
  level:
    root: info
    com:
      web:
        push: debug
  config: classpath:logback-local.xml   
  
publicKey: BDCuwEJaNg8f8UtTnD4yylmCuWsTCxxVoA-VXWExkxtCDC8U4yadV3aEUptbMvid_ctsDevpP-0NH40V-6AfW8k
privateKey: jcXlqHYI5CV9j4R1EF71kuptaHOEzMkz9PThic_6ee0 
  
